#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII

BW=1
bspc config border_width $BW
bspc config window_gap -$BW
for side in top right bottom left ; do
	bspc config ${side}_padding $BW
done
bspc config top_padding $(($BW + 30))

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config normal_border_color "#44475a" #dracula
#bspc config active_border_color "#bd93f9" #dracula
bspc config active_border_color "#6272a4" #dracula-cyan
#bspc config focused_border_color "#ff79c6" #dracula
bspc config focused_border_color "#8be9fd" #dracula-cyan
#bspc config focused_border_color "#0066BB" #my
bspc config presel_feedback_color "#6272a4" #dracula

bspc config pointer_follows_focus false
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^5' state=floating follow=on
#bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Pqiv state=floating

hsetroot
polybar mybar &
~/bin/script-notify-low-bat.sh &

